const PHRASE_TEMPLATES = [
    {
        structure: 'the {noun} {verb}, {noun2} {verb2}',
        nouns: ['veil', 'moon', 'wind', 'river', 'star', 'shadow', 'light', 'dream', 'silence', 'whisper', 'echo', 'mirror', 'gate', 'bridge', 'path', 'door', 'window', 'curtain', 'fog', 'mist', 'cloud', 'storm', 'thunder', 'lightning', 'rain', 'snow', 'frost', 'dew', 'dawn', 'dusk', 'twilight', 'sunrise', 'sunset', 'midnight', 'noon', 'hour', 'minute', 'second', 'moment', 'instant', 'eternity', 'infinity', 'crystal', 'gemstone', 'pearl', 'diamond', 'emerald', 'sapphire', 'ruby', 'opal', 'amethyst', 'topaz', 'obsidian', 'jade', 'turquoise', 'lapis', 'onyx', 'garnet', 'agate', 'carnelian', 'chrysoprase', 'moonstone', 'sunstone', 'bloodstone', 'tiger\'s eye', 'cat\'s eye', 'hawk\'s eye', 'falcon\'s eye', 'eagle\'s eye', 'wolf\'s eye', 'dragon\'s eye', 'phoenix\'s eye', 'unicorn\'s horn', 'dragon\'s scale', 'phoenix\'s feather', 'unicorn\'s mane', 'dragon\'s breath', 'phoenix\'s song', 'unicorn\'s tear', 'dragon\'s heart', 'phoenix\'s soul', 'unicorn\'s spirit'],
        verbs: ['thins', 'speaks', 'dances', 'flows', 'shimmers', 'whispers', 'glows', 'breathes', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'swirls', 'twirls', 'waltzes', 'leaps', 'bounds', 'springs', 'jumps', 'floats', 'drifts', 'wanders', 'roams', 'travels', 'journeys', 'explores', 'discovers', 'creates', 'destroys', 'builds', 'breaks', 'heals', 'wounds', 'blesses', 'curses', 'illuminates', 'darkens', 'transforms', 'manifests', 'materializes', 'dissolves', 'condenses', 'evaporates', 'pulses', 'beats', 'quivers', 'trembles', 'shakes', 'vibrates', 'resonates', 'echoes', 'reverberates', 'amplifies', 'diminishes', 'expands', 'contracts', 'ascends', 'descends', 'emerges', 'submerges', 'radiates', 'emanates', 'pulsates', 'oscillates', 'undulates', 'ripples', 'cascades', 'tumbles', 'spirals', 'orbits', 'waxes', 'wanes'],
        nouns2: ['truth', 'wisdom', 'destiny', 'fortune', 'clarity', 'peace', 'hope', 'love', 'courage', 'strength', 'beauty', 'grace', 'power', 'magic', 'mystery', 'serenity', 'harmony', 'balance', 'freedom', 'joy', 'sorrow', 'pain', 'pleasure', 'ecstasy', 'agony', 'bliss', 'misery', 'enlightenment', 'ignorance', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growth', 'aging', 'dying', 'living', 'compassion', 'empathy', 'kindness', 'generosity', 'humility', 'patience', 'perseverance', 'resilience', 'adaptability', 'creativity'],
        verbs2: ['glimmers', 'shines', 'flows', 'dances', 'speaks', 'whispers', 'glows', 'breathes', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'sparkles', 'twinkles', 'flickers', 'pulses', 'beats', 'quivers', 'trembles', 'shakes', 'vibrates', 'resonates', 'echoes', 'reverberates', 'amplifies', 'diminishes', 'grows', 'shrinks', 'expands', 'contracts', 'ascends', 'descends', 'emerges', 'submerges', 'radiates', 'emanates', 'pulsates', 'oscillates', 'undulates', 'ripples', 'cascades', 'tumbles', 'spirals', 'orbits']
    },
    {
      structure: 'you already {verb} the {noun}',
      verbs: ['know', 'feel', 'see', 'hear', 'sense', 'understand', 'remember', 'recognize', 'hold', 'carry', 'possess', 'own', 'embrace', 'accept', 'love', 'trust', 'believe', 'hope', 'dream', 'wish', 'desire', 'crave', 'long', 'yearn', 'ache', 'hurt', 'heal', 'grow', 'learn', 'teach', 'share', 'give', 'receive', 'create', 'destroy', 'build', 'break', 'mend', 'fix', 'solve', 'answer', 'question', 'wonder', 'doubt', 'perceive', 'intuit', 'foresee', 'anticipate', 'envision', 'imagine', 'conceive', 'realize', 'discover', 'uncover', 'grasp', 'comprehend', 'apprehend', 'fathom', 'penetrate', 'pierce', 'unlock', 'decode', 'decipher', 'interpret', 'translate', 'transform', 'transmute', 'alchemize', 'crystallize', 'manifest', 'materialize', 'dematerialize', 'etherealize', 'spiritualize', 'embody', 'incarnate', 'disincarnate', 'ascend', 'descend', 'transcend', 'descend', 'evolve', 'devolve', 'progress', 'regress', 'advance', 'retreat', 'expand', 'contract', 'dilate', 'constrict'],
      nouns: ['answer', 'truth', 'path', 'way', 'direction', 'purpose', 'meaning', 'reason', 'cause', 'source', 'root', 'heart', 'soul', 'spirit', 'essence', 'nature', 'form', 'shape', 'pattern', 'design', 'plan', 'strategy', 'method', 'approach', 'solution', 'problem', 'challenge', 'obstacle', 'barrier', 'wall', 'door', 'gate', 'bridge', 'tunnel', 'road', 'street', 'avenue', 'boulevard', 'highway', 'freeway', 'pathway', 'walkway', 'trail', 'compass', 'map', 'guide', 'signpost', 'milestone', 'landmark', 'beacon', 'lighthouse', 'star', 'constellation', 'north']
    },
    {
      structure: 'listen for the {adjective} {noun}',
      adjectives: ['softest', 'gentlest', 'quietest', 'sweetest', 'truest', 'purest', 'deepest', 'highest', 'brightest', 'clearest', 'strongest', 'wisest', 'kindest', 'bravest', 'loveliest', 'fairest', 'noblest', 'grandest', 'finest', 'best', 'darkest', 'lowest', 'weakest', 'foolish', 'cruelest', 'ugliest', 'meanest', 'worst', 'loudest', 'harshest', 'roughest', 'smoother', 'sharper', 'duller', 'faster', 'slower', 'hotter', 'colder', 'wetter', 'drier', 'heavier', 'lighter', 'most ethereal', 'most celestial', 'most divine', 'most sacred', 'most mystical', 'most enchanting', 'most mesmerizing', 'most captivating', 'most alluring', 'most bewitching'],
      nouns: ['yes', 'no', 'answer', 'voice', 'sound', 'whisper', 'call', 'song', 'word', 'message', 'sign', 'signal', 'hint', 'clue', 'truth', 'wisdom', 'guidance', 'direction', 'path', 'way', 'road', 'street', 'avenue', 'boulevard', 'highway', 'freeway', 'pathway', 'walkway', 'trail', 'track', 'route', 'course', 'journey', 'adventure', 'experience', 'lesson', 'gift', 'blessing', 'curse', 'reward', 'punishment', 'consequence', 'revelation', 'epiphany', 'awakening', 'realization', 'discovery', 'insight', 'foresight', 'prophecy', 'omen', 'portent', 'significance']
    },
    {
      structure: '{noun} {verb} the {noun2}',
      nouns: ['intention', 'focus', 'desire', 'hope', 'dream', 'wish', 'prayer', 'thought', 'mind', 'heart', 'soul', 'spirit', 'will', 'power', 'strength', 'courage', 'love', 'faith', 'trust', 'belief', 'doubt', 'fear', 'anger', 'hate', 'envy', 'jealousy', 'pride', 'humility', 'gratitude', 'forgiveness', 'mercy', 'justice', 'truth', 'honesty', 'integrity', 'honor', 'dignity', 'respect', 'admiration', 'appreciation', 'recognition', 'acknowledgment', 'determination', 'resolve', 'commitment', 'dedication', 'devotion', 'loyalty', 'fidelity', 'constancy', 'steadfastness', 'perseverance'],
      verbs: ['tunes', 'sets', 'aligns', 'matches', 'connects', 'joins', 'unites', 'harmonizes', 'balances', 'centers', 'grounds', 'elevates', 'raises', 'lifts', 'opens', 'expands', 'grows', 'develops', 'evolves', 'transforms', 'changes', 'alters', 'modifies', 'adjusts', 'adapts', 'conforms', 'resists', 'defies', 'challenges', 'accepts', 'rejects', 'embraces', 'denies', 'affirms', 'confirms', 'validates', 'invalidates', 'supports', 'opposes', 'helps', 'hinders', 'facilitates', 'orchestrates', 'conducts', 'directs', 'guides', 'steers', 'navigates', 'pilots', 'captains', 'leads', 'influences', 'shapes'],
      nouns2: ['frequency', 'vibration', 'energy', 'rhythm', 'flow', 'current', 'stream', 'wave', 'pulse', 'beat', 'harmony', 'balance', 'alignment', 'connection', 'unity', 'oneness', 'wholeness', 'completeness', 'perfection', 'beauty', 'ugliness', 'goodness', 'evil', 'right', 'wrong', 'truth', 'falsehood', 'reality', 'illusion', 'fact', 'fiction', 'myth', 'legend', 'story', 'tale', 'narrative', 'account', 'report', 'description', 'explanation', 'interpretation', 'understanding', 'resonance', 'synchronization', 'coherence', 'consonance', 'accord', 'concord', 'symmetry', 'proportion', 'equilibrium', 'stability', 'foundation']
    },
    {
      structure: '{noun} {verb} between {noun2}',
      nouns: ['destiny', 'fate', 'fortune', 'luck', 'chance', 'opportunity', 'possibility', 'potential', 'future', 'tomorrow', 'hope', 'dream', 'wish', 'prayer', 'thought', 'mind', 'heart', 'soul', 'spirit', 'body', 'flesh', 'bone', 'blood', 'breath', 'life', 'death', 'birth', 'rebirth', 'transformation', 'metamorphosis', 'evolution', 'revolution', 'revelation', 'apocalypse', 'enlightenment', 'awakening', 'realization', 'recognition', 'discovery', 'invention', 'creation', 'destruction', 'karma', 'dharma', 'samsara', 'nirvana', 'zen', 'tao', 'chi', 'prana', 'mana', 'essence', 'spark'],
      verbs: ['speaks', 'whispers', 'calls', 'sings', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'breathes', 'lives', 'dies', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'mediates', 'arbitrates', 'negotiates', 'reconciles', 'bridges', 'connects', 'links', 'joins', 'unifies', 'harmonizes', 'balances'],
      nouns2: ['thoughts', 'dreams', 'hopes', 'fears', 'doubts', 'beliefs', 'memories', 'visions', 'ideas', 'feelings', 'emotions', 'senses', 'moments', 'breaths', 'heartbeats', 'steps', 'moves', 'changes', 'shifts', 'flows', 'rivers', 'streams', 'oceans', 'seas', 'lakes', 'ponds', 'pools', 'springs', 'wells', 'fountains', 'waterfalls', 'rapids', 'whirlpools', 'eddies', 'currents', 'tides', 'waves', 'ripples', 'splashes', 'drops', 'tears', 'sweat', 'consciousness', 'awareness', 'mindfulness', 'presence', 'attention', 'focus', 'concentration', 'meditation', 'contemplation', 'reflection', 'introspection']
    },
    {
      structure: 'your {noun} is a {noun2}',
      nouns: ['timing', 'moment', 'time', 'hour', 'day', 'path', 'journey', 'story', 'life', 'destiny', 'fate', 'fortune', 'luck', 'chance', 'opportunity', 'possibility', 'potential', 'future', 'present', 'past', 'yesterday', 'tomorrow', 'tonight', 'morning', 'afternoon', 'evening', 'night', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'season', 'year', 'month', 'week', 'decade', 'century', 'millennium', 'eon'],
      nouns2: ['constellation', 'star', 'planet', 'galaxy', 'universe', 'cosmos', 'creation', 'miracle', 'wonder', 'beauty', 'grace', 'gift', 'blessing', 'treasure', 'jewel', 'pearl', 'diamond', 'gold', 'silver', 'crystal', 'gemstone', 'ruby', 'emerald', 'sapphire', 'opal', 'amethyst', 'topaz', 'garnet', 'jade', 'turquoise', 'lapis', 'onyx', 'obsidian', 'quartz', 'marble', 'granite', 'limestone', 'sandstone', 'clay', 'earth', 'stone', 'rock']
    },
    {
      structure: 'the next {noun} arrives on a {noun2}',
      nouns: ['step', 'move', 'change', 'shift', 'turn', 'moment', 'opportunity', 'chance', 'possibility', 'door', 'window', 'path', 'way', 'road', 'journey', 'adventure', 'experience', 'lesson', 'gift', 'blessing', 'curse', 'reward', 'punishment', 'consequence', 'result', 'outcome', 'effect', 'cause', 'reason', 'purpose', 'meaning', 'significance', 'importance', 'value', 'worth', 'price', 'cost', 'expense', 'investment', 'return', 'profit', 'loss'],
      nouns2: ['whisper', 'breath', 'sigh', 'laugh', 'smile', 'tear', 'song', 'dance', 'step', 'move', 'gesture', 'sign', 'signal', 'hint', 'clue', 'truth', 'wisdom', 'guidance', 'direction', 'path', 'road', 'street', 'avenue', 'boulevard', 'highway', 'freeway', 'pathway', 'walkway', 'trail', 'track', 'route', 'course', 'journey', 'adventure', 'experience', 'lesson', 'gift', 'blessing', 'curse', 'reward', 'punishment', 'consequence']
    },
    {
      structure: '{noun} {verb} at the {noun2}',
      nouns: ['clarity', 'truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'vision', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring', 'noticing', 'observing', 'watching', 'listening', 'speaking', 'singing', 'dancing', 'moving', 'standing', 'sitting', 'lying', 'walking'],
      verbs: ['shimmers', 'glows', 'shines', 'sparkles', 'twinkles', 'flickers', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'swirls', 'twirls', 'waltzes', 'leaps', 'bounds', 'springs', 'jumps', 'floats', 'drifts', 'wanders', 'roams', 'travels', 'journeys', 'explores', 'discovers', 'creates', 'destroys', 'builds', 'breaks', 'heals', 'wounds', 'blesses', 'curses'],
      nouns2: ['edges', 'borders', 'boundaries', 'limits', 'horizons', 'skies', 'heavens', 'depths', 'heights', 'centers', 'hearts', 'souls', 'spirits', 'minds', 'thoughts', 'dreams', 'hopes', 'fears', 'doubts', 'beliefs', 'memories', 'visions', 'ideas', 'feelings', 'emotions', 'senses', 'moments', 'breaths', 'heartbeats', 'steps', 'moves', 'changes', 'shifts', 'flows', 'rivers', 'streams', 'oceans', 'seas', 'lakes', 'ponds', 'pools', 'springs']
    },
    {
      structure: '{noun} {verb} in {adjective} {noun2}',
      nouns: ['fortune', 'luck', 'chance', 'opportunity', 'possibility', 'potential', 'future', 'tomorrow', 'hope', 'dream', 'wish', 'prayer', 'thought', 'mind', 'heart', 'soul', 'spirit', 'destiny', 'fate', 'beauty', 'ugliness', 'goodness', 'evil', 'right', 'wrong', 'truth', 'falsehood', 'reality', 'illusion', 'fact', 'fiction', 'myth', 'legend', 'story', 'tale', 'narrative', 'account', 'report', 'description', 'explanation', 'interpretation', 'understanding'],
      verbs: ['hums', 'sings', 'whispers', 'speaks', 'calls', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'breathes', 'lives', 'dies', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits'],
      adjectives: ['quiet', 'silent', 'still', 'peaceful', 'calm', 'serene', 'gentle', 'soft', 'tender', 'warm', 'cool', 'fresh', 'new', 'old', 'ancient', 'timeless', 'eternal', 'infinite', 'boundless', 'limitless', 'loud', 'noisy', 'chaotic', 'violent', 'aggressive', 'harsh', 'rough', 'sharp', 'dull', 'bright', 'dark', 'light', 'heavy', 'light', 'fast', 'slow', 'hot', 'cold', 'wet', 'dry', 'hard', 'soft'],
      nouns2: ['moments', 'times', 'hours', 'days', 'nights', 'seasons', 'years', 'ages', 'cycles', 'rhythms', 'flows', 'streams', 'currents', 'waves', 'pulses', 'beats', 'breaths', 'heartbeats', 'steps', 'moves', 'changes', 'shifts', 'flows', 'rivers', 'streams', 'oceans', 'seas', 'lakes', 'ponds', 'pools', 'springs', 'wells', 'fountains', 'waterfalls', 'rapids', 'whirlpools', 'eddies', 'currents', 'tides', 'waves', 'ripples', 'splashes']
    },
    {
      structure: '{verb} — the {noun} {verb2}',
      verbs: ['exhale', 'inhale', 'breathe', 'relax', 'let go', 'release', 'surrender', 'trust', 'believe', 'hope', 'dream', 'wish', 'pray', 'think', 'feel', 'sense', 'know', 'understand', 'remember', 'forget', 'learn', 'teach', 'grow', 'change', 'evolve', 'transform', 'heal', 'wound', 'bless', 'curse', 'help', 'hinder', 'guide', 'mislead', 'create', 'destroy', 'build', 'break', 'mend', 'split', 'unite', 'divide'],
      nouns: ['path', 'way', 'road', 'journey', 'adventure', 'experience', 'lesson', 'gift', 'blessing', 'treasure', 'jewel', 'pearl', 'diamond', 'gold', 'silver', 'crystal', 'star', 'planet', 'galaxy', 'universe', 'cosmos', 'creation', 'destruction', 'birth', 'death', 'life', 'soul', 'spirit', 'mind', 'heart', 'body', 'flesh', 'bone', 'blood', 'breath', 'thought', 'feeling', 'emotion', 'sense', 'memory', 'vision', 'dream'],
      verbs2: ['appears', 'reveals', 'shows', 'opens', 'unfolds', 'emerges', 'arises', 'comes', 'arrives', 'manifests', 'materializes', 'takes form', 'becomes real', 'comes true', 'happens', 'occurs', 'takes place', 'comes to pass', 'comes to be', 'comes to life', 'dies', 'fades', 'disappears', 'vanishes', 'dissolves', 'evaporates', 'condenses', 'freezes', 'melts', 'boils', 'cools', 'warms', 'heats', 'chills', 'burns', 'freezes', 'thaws', 'grows', 'decays', 'heals', 'wounds', 'blesses']
    },
    {
      structure: 'when {noun} meets {noun2}, {noun3} {verb}',
      nouns: ['light', 'darkness', 'day', 'night', 'sun', 'moon', 'fire', 'water', 'earth', 'air', 'spirit', 'matter', 'mind', 'body', 'heart', 'soul', 'truth', 'illusion', 'reality', 'dream', 'hope', 'fear', 'love', 'hate', 'joy', 'sorrow', 'peace', 'chaos', 'order', 'freedom', 'bondage', 'life', 'death', 'birth', 'rebirth', 'beginning', 'end', 'past', 'future', 'present', 'eternity'],
      nouns2: ['shadow', 'illumination', 'twilight', 'dawn', 'star', 'planet', 'ocean', 'mountain', 'forest', 'desert', 'valley', 'peak', 'depth', 'height', 'width', 'length', 'size', 'shape', 'form', 'essence', 'nature', 'character', 'personality', 'identity', 'self', 'other', 'stranger', 'friend', 'enemy', 'ally', 'adversary', 'teacher', 'student', 'master', 'servant', 'leader', 'follower'],
      nouns3: ['magic', 'wonder', 'mystery', 'beauty', 'truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring'],
      verbs: ['appears', 'emerges', 'arises', 'comes', 'arrives', 'manifests', 'materializes', 'takes form', 'becomes real', 'comes true', 'happens', 'occurs', 'takes place', 'comes to pass', 'comes to be', 'comes to life', 'dies', 'fades', 'disappears', 'vanishes', 'dissolves', 'evaporates', 'condenses', 'freezes', 'melts', 'boils', 'cools', 'warms', 'heats', 'chills', 'burns', 'freezes', 'thaws', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads']
    },
    {
      structure: 'the {adjective} {noun} {verb} {adjective2} {noun2}',
      adjectives: ['ancient', 'timeless', 'eternal', 'infinite', 'boundless', 'limitless', 'endless', 'ceaseless', 'incessant', 'perpetual', 'constant', 'steady', 'stable', 'firm', 'solid', 'strong', 'powerful', 'mighty', 'great', 'grand', 'noble', 'wise', 'intelligent', 'clever', 'smart', 'brilliant', 'genius', 'gifted', 'talented', 'skilled', 'experienced', 'mature', 'grown', 'developed', 'evolved', 'advanced', 'sophisticated', 'complex', 'simple', 'basic', 'fundamental', 'essential'],
      nouns: ['wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring', 'noticing', 'observing', 'watching', 'listening', 'speaking', 'singing', 'dancing', 'moving', 'standing', 'sitting', 'lying', 'walking', 'running', 'flying', 'swimming'],
      verbs: ['creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens', 'secures', 'releases', 'holds', 'lets go', 'grasps', 'releases', 'embraces', 'rejects', 'accepts', 'denies', 'affirms', 'confirms', 'validates', 'invalidates', 'supports', 'opposes', 'helps', 'hinders', 'facilitates', 'obstructs', 'enables', 'disables'],
      adjectives2: ['new', 'fresh', 'young', 'youthful', 'childlike', 'innocent', 'pure', 'clean', 'clear', 'bright', 'shining', 'glowing', 'radiant', 'luminous', 'brilliant', 'sparkling', 'twinkling', 'flickering', 'dancing', 'flowing', 'moving', 'shifting', 'changing', 'evolving', 'growing', 'developing', 'maturing', 'aging', 'decaying', 'dying', 'dead', 'lifeless', 'motionless', 'still', 'quiet', 'silent', 'peaceful', 'calm', 'serene', 'tranquil', 'placid', 'smooth'],
      nouns2: ['possibility', 'potential', 'opportunity', 'chance', 'luck', 'fortune', 'destiny', 'fate', 'future', 'tomorrow', 'hope', 'dream', 'wish', 'prayer', 'thought', 'mind', 'heart', 'soul', 'spirit', 'body', 'flesh', 'bone', 'blood', 'breath', 'life', 'death', 'birth', 'rebirth', 'transformation', 'metamorphosis', 'evolution', 'revolution', 'revelation', 'apocalypse', 'enlightenment', 'awakening', 'realization', 'recognition', 'discovery', 'invention', 'creation', 'destruction']
    },
    {
      structure: 'in the {adjective} {noun}, {noun2} {verb}',
      adjectives: ['deepest', 'darkest', 'brightest', 'lightest', 'highest', 'lowest', 'farthest', 'nearest', 'oldest', 'newest', 'youngest', 'eldest', 'wisest', 'foolish', 'kindest', 'cruelest', 'gentlest', 'harshest', 'softest', 'hardest', 'sweetest', 'bitterest', 'happiest', 'saddest', 'richest', 'poorest', 'strongest', 'weakest', 'fastest', 'slowest', 'hottest', 'coldest', 'wettest', 'driest', 'heaviest', 'lightest', 'biggest', 'smallest', 'longest', 'shortest', 'widest', 'narrowest'],
      nouns: ['darkness', 'light', 'shadow', 'illumination', 'silence', 'sound', 'stillness', 'motion', 'emptiness', 'fullness', 'absence', 'presence', 'void', 'substance', 'nothingness', 'everything', 'beginning', 'end', 'past', 'future', 'present', 'eternity', 'moment', 'instant', 'second', 'minute', 'hour', 'day', 'night', 'morning', 'evening', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'season', 'year', 'month', 'week', 'decade'],
      nouns2: ['truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring', 'noticing', 'observing', 'watching', 'listening', 'speaking', 'singing', 'dancing', 'moving', 'standing', 'sitting', 'lying', 'walking', 'running', 'flying'],
      verbs: ['speaks', 'whispers', 'calls', 'sings', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'breathes', 'lives', 'dies', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites']
    },
    {
      structure: 'every {noun} has a {noun2}',
      nouns: ['journey', 'path', 'road', 'way', 'adventure', 'experience', 'lesson', 'gift', 'blessing', 'curse', 'reward', 'punishment', 'consequence', 'result', 'outcome', 'effect', 'cause', 'reason', 'purpose', 'meaning', 'significance', 'importance', 'value', 'worth', 'price', 'cost', 'expense', 'investment', 'return', 'profit', 'loss', 'gain', 'benefit', 'advantage', 'disadvantage', 'strength', 'weakness', 'power', 'weakness', 'courage', 'fear', 'hope', 'despair'],
      nouns2: ['beginning', 'end', 'middle', 'center', 'heart', 'soul', 'spirit', 'essence', 'core', 'foundation', 'base', 'root', 'source', 'origin', 'destination', 'goal', 'aim', 'target', 'objective', 'purpose', 'reason', 'cause', 'motivation', 'inspiration', 'drive', 'force', 'energy', 'power', 'strength', 'weakness', 'advantage', 'disadvantage', 'benefit', 'drawback', 'positive', 'negative', 'good', 'bad', 'right', 'wrong', 'truth', 'falsehood']
    },
    {
      structure: 'the {noun} that {verb} is the {noun2} that {verb2}',
      nouns: ['question', 'answer', 'problem', 'solution', 'challenge', 'opportunity', 'obstacle', 'path', 'barrier', 'gate', 'door', 'window', 'opening', 'closing', 'beginning', 'end', 'start', 'finish', 'first', 'last', 'best', 'worst', 'highest', 'lowest', 'deepest', 'shallowest', 'strongest', 'weakest', 'fastest', 'slowest', 'hottest', 'coldest', 'brightest', 'darkest', 'loudest', 'quietest', 'sweetest', 'bitterest'],
      verbs: ['asks', 'seeks', 'finds', 'discovers', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens', 'secures', 'releases', 'holds', 'lets go', 'grasps', 'releases', 'embraces', 'rejects', 'accepts', 'denies', 'affirms', 'confirms', 'validates', 'invalidates', 'supports', 'opposes', 'helps', 'hinders'],
      nouns2: ['answer', 'question', 'solution', 'problem', 'path', 'obstacle', 'gate', 'barrier', 'door', 'window', 'opening', 'closing', 'end', 'beginning', 'finish', 'start', 'last', 'first', 'worst', 'best', 'lowest', 'highest', 'shallowest', 'deepest', 'weakest', 'strongest', 'slowest', 'fastest', 'coldest', 'hottest', 'darkest', 'brightest', 'quietest', 'loudest', 'bitterest', 'sweetest'],
      verbs2: ['answers', 'responds', 'replies', 'reacts', 'acts', 'moves', 'changes', 'grows', 'evolves', 'transforms', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens']
    },
    {
      structure: 'what {verb} in {noun} {verb2} in {noun2}',
      nouns: ['darkness', 'light', 'shadow', 'illumination', 'silence', 'sound', 'stillness', 'motion', 'emptiness', 'fullness', 'absence', 'presence', 'void', 'substance', 'nothingness', 'everything', 'beginning', 'end', 'past', 'future', 'present', 'eternity', 'moment', 'instant', 'second', 'minute', 'hour', 'day', 'night', 'morning', 'evening', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'season', 'year', 'month', 'week', 'decade'],
      verbs: ['begins', 'ends', 'starts', 'finishes', 'opens', 'closes', 'rises', 'falls', 'ascends', 'descends', 'emerges', 'submerges', 'appears', 'disappears', 'comes', 'goes', 'arrives', 'departs', 'enters', 'exits', 'approaches', 'recedes', 'advances', 'retreats', 'progresses', 'regresses', 'grows', 'decays', 'expands', 'contracts', 'increases', 'decreases', 'multiplies', 'divides', 'adds', 'subtracts', 'creates', 'destroys'],
      nouns2: ['truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring', 'noticing', 'observing', 'watching', 'listening', 'speaking', 'singing', 'dancing', 'moving', 'standing', 'sitting', 'lying', 'walking', 'running', 'flying'],
      verbs2: ['awakens', 'sleeps', 'dreams', 'wakes', 'rises', 'sets', 'shines', 'fades', 'glows', 'dim', 'sparkles', 'tarnishes', 'dances', 'stills', 'flows', 'stagnates', 'moves', 'stops', 'changes', 'remains', 'grows', 'shrinks', 'expands', 'contracts', 'opens', 'closes', 'reveals', 'hides', 'shows', 'conceals', 'expresses', 'suppresses', 'releases', 'holds', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits']
    },
    {
      structure: 'the {noun} of {noun2} is the {noun3} of {noun4}',
      nouns: ['beginning', 'end', 'start', 'finish', 'first', 'last', 'best', 'worst', 'highest', 'lowest', 'deepest', 'shallowest', 'strongest', 'weakest', 'fastest', 'slowest', 'hottest', 'coldest', 'brightest', 'darkest', 'loudest', 'quietest', 'sweetest', 'bitterest', 'richest', 'poorest', 'wisest', 'foolish', 'kindest', 'cruelest', 'gentlest', 'harshest', 'softest', 'hardest', 'biggest', 'smallest', 'longest', 'shortest', 'widest', 'narrowest'],
      nouns2: ['light', 'darkness', 'day', 'night', 'sun', 'moon', 'fire', 'water', 'earth', 'air', 'spirit', 'matter', 'mind', 'body', 'heart', 'soul', 'truth', 'illusion', 'reality', 'dream', 'hope', 'fear', 'love', 'hate', 'joy', 'sorrow', 'peace', 'chaos', 'order', 'freedom', 'bondage', 'life', 'death', 'birth', 'rebirth', 'past', 'future', 'present', 'eternity', 'moment', 'instant'],
      nouns3: ['end', 'beginning', 'finish', 'start', 'last', 'first', 'worst', 'best', 'lowest', 'highest', 'shallowest', 'deepest', 'weakest', 'strongest', 'slowest', 'fastest', 'coldest', 'hottest', 'darkest', 'brightest', 'quietest', 'loudest', 'bitterest', 'sweetest', 'poorest', 'richest', 'foolish', 'wisest', 'cruelest', 'kindest', 'harshest', 'gentlest', 'hardest', 'softest', 'smallest', 'biggest', 'shortest', 'longest', 'narrowest', 'widest'],
      nouns4: ['darkness', 'light', 'night', 'day', 'moon', 'sun', 'water', 'fire', 'earth', 'air', 'matter', 'spirit', 'body', 'mind', 'soul', 'heart', 'illusion', 'truth', 'dream', 'reality', 'fear', 'hope', 'hate', 'love', 'sorrow', 'joy', 'chaos', 'peace', 'bondage', 'freedom', 'order', 'death', 'life', 'rebirth', 'birth', 'future', 'past', 'instant', 'moment', 'eternity', 'present']
    },
    {
      structure: 'where {noun} {verb}, {noun2} {verb2}',
      nouns: ['light', 'darkness', 'day', 'night', 'sun', 'moon', 'fire', 'water', 'earth', 'air', 'spirit', 'matter', 'mind', 'body', 'heart', 'soul', 'truth', 'illusion', 'reality', 'dream', 'hope', 'fear', 'love', 'hate', 'joy', 'sorrow', 'peace', 'chaos', 'order', 'freedom', 'bondage', 'life', 'death', 'birth', 'rebirth', 'past', 'future', 'present', 'eternity', 'moment', 'instant'],
      verbs: ['shines', 'fades', 'glows', 'dim', 'sparkles', 'tarnishes', 'dances', 'stills', 'flows', 'stagnates', 'moves', 'stops', 'changes', 'remains', 'grows', 'shrinks', 'expands', 'contracts', 'opens', 'closes', 'reveals', 'hides', 'shows', 'conceals', 'expresses', 'suppresses', 'releases', 'holds', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects'],
      nouns2: ['shadow', 'illumination', 'twilight', 'dawn', 'star', 'planet', 'ocean', 'mountain', 'forest', 'desert', 'valley', 'peak', 'depth', 'height', 'width', 'length', 'size', 'shape', 'form', 'essence', 'nature', 'character', 'personality', 'identity', 'self', 'other', 'stranger', 'friend', 'enemy', 'ally', 'adversary', 'teacher', 'student', 'master', 'servant', 'leader', 'follower', 'guide', 'traveler', 'explorer', 'discoverer'],
      verbs2: ['appears', 'emerges', 'arises', 'comes', 'arrives', 'manifests', 'materializes', 'takes form', 'becomes real', 'comes true', 'happens', 'occurs', 'takes place', 'comes to pass', 'comes to be', 'comes to life', 'dies', 'fades', 'disappears', 'vanishes', 'dissolves', 'evaporates', 'condenses', 'freezes', 'melts', 'boils', 'cools', 'warms', 'heats', 'chills', 'burns', 'freezes', 'thaws', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads']
    },
    {
      structure: 'the {adjective} {noun} never {verb}',
      adjectives: ['wise', 'foolish', 'kind', 'cruel', 'gentle', 'harsh', 'soft', 'hard', 'sweet', 'bitter', 'rich', 'poor', 'strong', 'weak', 'fast', 'slow', 'hot', 'cold', 'bright', 'dark', 'loud', 'quiet', 'big', 'small', 'long', 'short', 'wide', 'narrow', 'deep', 'shallow', 'high', 'low', 'far', 'near', 'old', 'new', 'young', 'ancient', 'modern', 'timeless', 'temporary', 'eternal', 'finite'],
      nouns: ['sage', 'fool', 'teacher', 'student', 'master', 'servant', 'leader', 'follower', 'guide', 'traveler', 'explorer', 'discoverer', 'creator', 'destroyer', 'builder', 'breaker', 'healer', 'wounder', 'blesser', 'curser', 'helper', 'hinderer', 'supporter', 'opposer', 'friend', 'enemy', 'ally', 'adversary', 'stranger', 'acquaintance', 'lover', 'hater', 'believer', 'doubter', 'hopeful', 'despairing', 'peaceful', 'warlike', 'orderly', 'chaotic', 'free', 'bound'],
      verbs: ['sleeps', 'wakes', 'dreams', 'awakens', 'rises', 'sets', 'shines', 'fades', 'glows', 'dim', 'sparkles', 'tarnishes', 'dances', 'stills', 'flows', 'stagnates', 'moves', 'stops', 'changes', 'remains', 'grows', 'shrinks', 'expands', 'contracts', 'opens', 'closes', 'reveals', 'hides', 'shows', 'conceals', 'expresses', 'suppresses', 'releases', 'holds', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits']
    },
    {
      structure: 'beneath the {adjective} {noun}, {noun2} {verb}',
      adjectives: ['veiled', 'hidden', 'secret', 'mysterious', 'ancient', 'forgotten', 'buried', 'concealed', 'obscured', 'shrouded', 'masked', 'disguised', 'camouflaged', 'invisible', 'transparent', 'translucent', 'opaque', 'clear', 'foggy', 'misty', 'cloudy', 'stormy', 'calm', 'peaceful', 'turbulent', 'serene', 'chaotic', 'orderly', 'structured', 'random', 'organized'],
      nouns: ['surface', 'appearance', 'facade', 'mask', 'veil', 'curtain', 'screen', 'wall', 'barrier', 'boundary', 'limit', 'horizon', 'edge', 'border', 'line', 'divide', 'separation', 'connection', 'bridge', 'gate', 'door', 'window', 'opening', 'passage', 'path', 'road', 'way', 'journey', 'adventure', 'quest', 'mission'],
      nouns2: ['truth', 'reality', 'essence', 'core', 'heart', 'soul', 'spirit', 'nature', 'character', 'identity', 'purpose', 'meaning', 'significance', 'importance', 'value', 'worth', 'beauty', 'ugliness', 'goodness', 'evil', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting'],
      verbs: ['whispers', 'speaks', 'sings', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'breathes', 'lives', 'dies', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads']
    },
    {
      structure: 'the {noun} that {verb} is also the {noun2} that {verb2}',
      nouns: ['question', 'answer', 'problem', 'solution', 'challenge', 'opportunity', 'obstacle', 'path', 'barrier', 'gate', 'door', 'window', 'opening', 'closing', 'beginning', 'end', 'start', 'finish', 'first', 'last', 'best', 'worst', 'highest', 'lowest', 'deepest', 'shallowest', 'strongest', 'weakest', 'fastest', 'slowest', 'hottest', 'coldest', 'brightest', 'darkest', 'loudest', 'quietest', 'sweetest', 'bitterest'],
      verbs: ['asks', 'seeks', 'finds', 'discovers', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens', 'secures', 'releases', 'holds', 'lets go', 'grasps', 'releases', 'embraces', 'rejects', 'accepts', 'denies', 'affirms', 'confirms', 'validates', 'invalidates', 'supports', 'opposes', 'helps', 'hinders'],
      nouns2: ['answer', 'question', 'solution', 'problem', 'path', 'obstacle', 'gate', 'barrier', 'door', 'window', 'opening', 'closing', 'end', 'beginning', 'finish', 'start', 'last', 'first', 'worst', 'best', 'lowest', 'highest', 'shallowest', 'deepest', 'weakest', 'strongest', 'slowest', 'fastest', 'coldest', 'hottest', 'darkest', 'brightest', 'quietest', 'loudest', 'bitterest', 'sweetest'],
      verbs2: ['answers', 'responds', 'replies', 'reacts', 'acts', 'moves', 'changes', 'grows', 'evolves', 'transforms', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens']
    },
    {
      structure: 'in the {adjective} {noun}, {noun2} becomes {noun3}',
      adjectives: ['deepest', 'darkest', 'brightest', 'lightest', 'highest', 'lowest', 'farthest', 'nearest', 'oldest', 'newest', 'youngest', 'eldest', 'wisest', 'foolish', 'kindest', 'cruelest', 'gentlest', 'harshest', 'softest', 'hardest', 'sweetest', 'bitterest', 'happiest', 'saddest', 'richest', 'poorest', 'strongest', 'weakest', 'fastest', 'slowest', 'hottest', 'coldest', 'wettest', 'driest', 'heaviest', 'lightest', 'biggest', 'smallest', 'longest', 'shortest', 'widest', 'narrowest'],
      nouns: ['darkness', 'light', 'shadow', 'illumination', 'silence', 'sound', 'stillness', 'motion', 'emptiness', 'fullness', 'absence', 'presence', 'void', 'substance', 'nothingness', 'everything', 'beginning', 'end', 'past', 'future', 'present', 'eternity', 'moment', 'instant', 'second', 'minute', 'hour', 'day', 'night', 'morning', 'evening', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'season', 'year', 'month', 'week', 'decade'],
      nouns2: ['truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring', 'noticing', 'observing', 'watching', 'listening', 'speaking', 'singing', 'dancing', 'moving', 'standing', 'sitting', 'lying', 'walking', 'running', 'flying'],
      nouns3: ['illusion', 'reality', 'dream', 'nightmare', 'fantasy', 'fact', 'fiction', 'myth', 'legend', 'story', 'tale', 'narrative', 'account', 'report', 'description', 'explanation', 'interpretation', 'understanding', 'misunderstanding', 'confusion', 'clarity', 'obscurity', 'transparency', 'opacity', 'visibility', 'invisibility', 'presence', 'absence', 'existence', 'nonexistence']
    },
    {
      structure: 'the {noun} speaks in {adjective} {noun2}',
      nouns: ['oracle', 'prophet', 'sage', 'seer', 'mystic', 'shaman', 'wizard', 'warlock', 'witch', 'enchanter', 'sorcerer', 'magician', 'conjurer', 'diviner', 'augur', 'soothsayer', 'fortune-teller', 'palm-reader', 'astrologer', 'numerologist', 'tarot-reader', 'medium', 'channeler', 'healer', 'teacher', 'guide', 'mentor', 'master', 'guru', 'swami', 'lama', 'monk', 'priest', 'priestess', 'druid', 'bard', 'minstrel', 'troubadour'],
      adjectives: ['whispered', 'silent', 'loud', 'soft', 'gentle', 'harsh', 'sweet', 'bitter', 'warm', 'cold', 'bright', 'dark', 'clear', 'muddy', 'pure', 'impure', 'ancient', 'modern', 'timeless', 'temporary', 'eternal', 'finite', 'infinite', 'boundless', 'limited', 'expansive', 'contracted', 'flowing', 'stagnant', 'moving', 'still', 'alive', 'dead', 'awake', 'sleeping', 'conscious', 'unconscious'],
      nouns2: ['tongues', 'languages', 'words', 'phrases', 'sentences', 'verses', 'poems', 'songs', 'chants', 'mantras', 'prayers', 'blessings', 'curses', 'prophecies', 'predictions', 'foretellings', 'visions', 'dreams', 'revelations', 'truths', 'lies', 'secrets', 'mysteries', 'riddles', 'puzzles', 'enigmas', 'paradoxes', 'contradictions', 'harmonies', 'dissonances', 'rhythms', 'melodies', 'symphonies', 'concertos', 'sonatas', 'arias', 'ballads', 'hymns', 'anthems']
    },
    {
      structure: 'when {noun} {verb}, {noun2} {verb2}',
      nouns: ['light', 'darkness', 'day', 'night', 'sun', 'moon', 'fire', 'water', 'earth', 'air', 'spirit', 'matter', 'mind', 'body', 'heart', 'soul', 'truth', 'illusion', 'reality', 'dream', 'hope', 'fear', 'love', 'hate', 'joy', 'sorrow', 'peace', 'chaos', 'order', 'freedom', 'bondage', 'life', 'death', 'birth', 'rebirth', 'beginning', 'end', 'past', 'future', 'present', 'eternity'],
      verbs: ['shines', 'fades', 'glows', 'dim', 'sparkles', 'tarnishes', 'dances', 'stills', 'flows', 'stagnates', 'moves', 'stops', 'changes', 'remains', 'grows', 'shrinks', 'expands', 'contracts', 'opens', 'closes', 'reveals', 'hides', 'shows', 'conceals', 'expresses', 'suppresses', 'releases', 'holds', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects'],
      nouns2: ['shadow', 'illumination', 'twilight', 'dawn', 'star', 'planet', 'ocean', 'mountain', 'forest', 'desert', 'valley', 'peak', 'depth', 'height', 'width', 'length', 'size', 'shape', 'form', 'essence', 'nature', 'character', 'personality', 'identity', 'self', 'other', 'stranger', 'friend', 'enemy', 'ally', 'adversary', 'teacher', 'student', 'master', 'servant', 'leader', 'follower', 'guide', 'traveler', 'explorer', 'discoverer'],
      verbs2: ['appears', 'emerges', 'arises', 'comes', 'arrives', 'manifests', 'materializes', 'takes form', 'becomes real', 'comes true', 'happens', 'occurs', 'takes place', 'comes to pass', 'comes to be', 'comes to life', 'dies', 'fades', 'disappears', 'vanishes', 'dissolves', 'evaporates', 'condenses', 'freezes', 'melts', 'boils', 'cools', 'warms', 'heats', 'chills', 'burns', 'freezes', 'thaws', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads']
    },
    {
      structure: 'the {noun} of {noun2} {verb} the {noun3}',
      nouns: ['beginning', 'end', 'start', 'finish', 'first', 'last', 'best', 'worst', 'highest', 'lowest', 'deepest', 'shallowest', 'strongest', 'weakest', 'fastest', 'slowest', 'hottest', 'coldest', 'brightest', 'darkest', 'loudest', 'quietest', 'sweetest', 'bitterest', 'richest', 'poorest', 'wisest', 'foolish', 'kindest', 'cruelest', 'gentlest', 'harshest', 'softest', 'hardest', 'biggest', 'smallest', 'longest', 'shortest', 'widest', 'narrowest'],
      nouns2: ['light', 'darkness', 'day', 'night', 'sun', 'moon', 'fire', 'water', 'earth', 'air', 'spirit', 'matter', 'mind', 'body', 'heart', 'soul', 'truth', 'illusion', 'reality', 'dream', 'hope', 'fear', 'love', 'hate', 'joy', 'sorrow', 'peace', 'chaos', 'order', 'freedom', 'bondage', 'life', 'death', 'birth', 'rebirth', 'past', 'future', 'present', 'eternity', 'moment', 'instant'],
      verbs: ['illuminates', 'darkens', 'reveals', 'conceals', 'shows', 'hides', 'exposes', 'covers', 'uncovers', 'discloses', 'withholds', 'shares', 'keeps', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens', 'secures', 'releases', 'holds', 'lets go'],
      nouns3: ['path', 'way', 'road', 'journey', 'adventure', 'experience', 'lesson', 'gift', 'blessing', 'curse', 'reward', 'punishment', 'consequence', 'result', 'outcome', 'effect', 'cause', 'reason', 'purpose', 'meaning', 'significance', 'importance', 'value', 'worth', 'price', 'cost', 'expense', 'investment', 'return', 'profit', 'loss', 'gain', 'benefit', 'advantage', 'disadvantage', 'strength', 'weakness', 'power', 'weakness', 'courage', 'fear', 'hope', 'despair']
    },
    {
      structure: 'your {noun} {verb} like a {noun2}',
      nouns: ['timing', 'moment', 'time', 'hour', 'day', 'path', 'journey', 'story', 'life', 'destiny', 'fate', 'fortune', 'luck', 'chance', 'opportunity', 'possibility', 'potential', 'future', 'present', 'past', 'yesterday', 'tomorrow', 'tonight', 'morning', 'afternoon', 'evening', 'night', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'season', 'year', 'month', 'week', 'decade', 'century', 'millennium', 'eon'],
      verbs: ['flows', 'moves', 'dances', 'swims', 'flies', 'runs', 'walks', 'crawls', 'leaps', 'bounds', 'springs', 'jumps', 'floats', 'drifts', 'wanders', 'roams', 'travels', 'journeys', 'explores', 'discovers', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens', 'secures', 'releases'],
      nouns2: ['river', 'stream', 'ocean', 'sea', 'lake', 'pond', 'pool', 'spring', 'well', 'fountain', 'waterfall', 'rapid', 'whirlpool', 'eddy', 'current', 'tide', 'wave', 'ripple', 'splash', 'drop', 'tear', 'sweat', 'rain', 'snow', 'hail', 'sleet', 'frost', 'dew', 'mist', 'fog', 'cloud', 'storm', 'thunder', 'lightning', 'wind', 'breeze', 'gust', 'hurricane', 'tornado', 'cyclone', 'typhoon', 'monsoon', 'trade wind']
    },
    {
      structure: 'the {noun} knows what the {noun2} {verb}',
      nouns: ['oracle', 'prophet', 'sage', 'seer', 'mystic', 'shaman', 'wizard', 'warlock', 'witch', 'enchanter', 'sorcerer', 'magician', 'conjurer', 'diviner', 'augur', 'soothsayer', 'fortune-teller', 'palm-reader', 'astrologer', 'numerologist', 'tarot-reader', 'medium', 'channeler', 'healer', 'teacher', 'guide', 'mentor', 'master', 'guru', 'swami', 'lama', 'monk', 'priest', 'priestess', 'druid', 'bard', 'minstrel', 'troubadour'],
      nouns2: ['heart', 'soul', 'spirit', 'mind', 'body', 'flesh', 'bone', 'blood', 'breath', 'life', 'death', 'birth', 'rebirth', 'transformation', 'metamorphosis', 'evolution', 'revolution', 'revelation', 'apocalypse', 'enlightenment', 'awakening', 'realization', 'recognition', 'discovery', 'invention', 'creation', 'destruction', 'beginning', 'end', 'start', 'finish', 'first', 'last', 'best', 'worst', 'highest', 'lowest', 'deepest', 'shallowest', 'strongest', 'weakest'],
      verbs: ['whispers', 'speaks', 'calls', 'sings', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'breathes', 'lives', 'dies', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites']
    },
    {
      structure: 'between {noun} and {noun2}, {noun3} {verb}',
      nouns: ['light', 'darkness', 'day', 'night', 'sun', 'moon', 'fire', 'water', 'earth', 'air', 'spirit', 'matter', 'mind', 'body', 'heart', 'soul', 'truth', 'illusion', 'reality', 'dream', 'hope', 'fear', 'love', 'hate', 'joy', 'sorrow', 'peace', 'chaos', 'order', 'freedom', 'bondage', 'life', 'death', 'birth', 'rebirth', 'beginning', 'end', 'past', 'future', 'present', 'eternity'],
      nouns2: ['shadow', 'illumination', 'twilight', 'dawn', 'star', 'planet', 'ocean', 'mountain', 'forest', 'desert', 'valley', 'peak', 'depth', 'height', 'width', 'length', 'size', 'shape', 'form', 'essence', 'nature', 'character', 'personality', 'identity', 'self', 'other', 'stranger', 'friend', 'enemy', 'ally', 'adversary', 'teacher', 'student', 'master', 'servant', 'leader', 'follower', 'guide', 'traveler', 'explorer', 'discoverer'],
      nouns3: ['magic', 'wonder', 'mystery', 'beauty', 'truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring'],
      verbs: ['appears', 'emerges', 'arises', 'comes', 'arrives', 'manifests', 'materializes', 'takes form', 'becomes real', 'comes true', 'happens', 'occurs', 'takes place', 'comes to pass', 'comes to be', 'comes to life', 'dies', 'fades', 'disappears', 'vanishes', 'dissolves', 'evaporates', 'condenses', 'freezes', 'melts', 'boils', 'cools', 'warms', 'heats', 'chills', 'burns', 'freezes', 'thaws', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads']
    },
    {
      structure: 'the {noun} that {verb} in {noun2}',
      nouns: ['truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring', 'noticing', 'observing', 'watching', 'listening', 'speaking', 'singing', 'dancing', 'moving', 'standing', 'sitting', 'lying', 'walking', 'running', 'flying'],
      verbs: ['dwells', 'resides', 'lives', 'exists', 'thrives', 'flourishes', 'grows', 'develops', 'evolves', 'transforms', 'changes', 'remains', 'stays', 'lingers', 'persists', 'endures', 'survives', 'prospers', 'succeeds', 'fails', 'struggles', 'suffers', 'enjoys', 'celebrates', 'mourns', 'weeps', 'laughs', 'smiles', 'frowns', 'sighs', 'breathes', 'dreams', 'awakens', 'sleeps', 'rests', 'works', 'plays', 'creates', 'destroys', 'builds', 'breaks', 'mends'],
      nouns2: ['darkness', 'light', 'shadow', 'illumination', 'silence', 'sound', 'stillness', 'motion', 'emptiness', 'fullness', 'absence', 'presence', 'void', 'substance', 'nothingness', 'everything', 'beginning', 'end', 'past', 'future', 'present', 'eternity', 'moment', 'instant', 'second', 'minute', 'hour', 'day', 'night', 'morning', 'evening', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'season', 'year', 'month', 'week', 'decade']
    },
    {
      structure: 'through {noun} comes {noun2}',
      nouns: ['suffering', 'pain', 'struggle', 'hardship', 'difficulty', 'challenge', 'obstacle', 'barrier', 'wall', 'mountain', 'ocean', 'desert', 'forest', 'valley', 'abyss', 'darkness', 'night', 'winter', 'storm', 'chaos', 'confusion', 'doubt', 'fear', 'despair', 'sorrow', 'grief', 'loss', 'death', 'end', 'destruction', 'ruin', 'fall', 'descent', 'decline', 'decay', 'corruption', 'evil', 'sin', 'guilt', 'shame', 'regret', 'remorse'],
      nouns2: ['wisdom', 'strength', 'courage', 'hope', 'faith', 'love', 'peace', 'joy', 'happiness', 'contentment', 'fulfillment', 'enlightenment', 'awakening', 'realization', 'understanding', 'knowledge', 'insight', 'clarity', 'vision', 'foresight', 'hindsight', 'memory', 'learning', 'growth', 'transformation', 'metamorphosis', 'evolution', 'revolution', 'revelation', 'apocalypse', 'resurrection', 'rebirth', 'renewal', 'restoration', 'healing', 'redemption', 'salvation', 'grace', 'mercy', 'forgiveness', 'acceptance', 'embrace']
    },
    {
      structure: 'the {adjective} {noun} {verb} the {adjective2} {noun2}',
      adjectives: ['ancient', 'eternal', 'timeless', 'immortal', 'divine', 'sacred', 'holy', 'blessed', 'cursed', 'enchanted', 'magical', 'mystical', 'spiritual', 'ethereal', 'celestial', 'cosmic', 'universal', 'infinite', 'boundless', 'limitless', 'endless', 'perpetual', 'constant', 'steady', 'stable', 'firm', 'solid', 'strong', 'powerful', 'mighty', 'majestic', 'noble', 'honorable', 'virtuous', 'pure', 'innocent', 'wise', 'enlightened', 'awakened', 'conscious', 'aware', 'mindful'],
      nouns: ['oracle', 'prophet', 'sage', 'seer', 'mystic', 'shaman', 'wizard', 'warlock', 'witch', 'enchanter', 'sorcerer', 'magician', 'conjurer', 'diviner', 'augur', 'soothsayer', 'fortune-teller', 'palm-reader', 'astrologer', 'numerologist', 'tarot-reader', 'medium', 'channeler', 'healer', 'teacher', 'guide', 'mentor', 'master', 'guru', 'swami', 'lama', 'monk', 'priest', 'priestess', 'druid', 'bard', 'minstrel', 'troubadour'],
      verbs: ['illuminates', 'darkens', 'reveals', 'conceals', 'shows', 'hides', 'exposes', 'covers', 'uncovers', 'discloses', 'withholds', 'shares', 'keeps', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites', 'divides', 'joins', 'separates', 'connects', 'disconnects', 'links', 'unlinks', 'binds', 'unbinds', 'ties', 'unties', 'fastens', 'unfastens', 'secures', 'releases', 'holds', 'lets go', 'embraces', 'rejects', 'accepts', 'denies'],
      adjectives2: ['hidden', 'secret', 'mysterious', 'obscure', 'veiled', 'concealed', 'buried', 'forgotten', 'lost', 'abandoned', 'neglected', 'ignored', 'overlooked', 'missed', 'unnoticed', 'unseen', 'invisible', 'transparent', 'translucent', 'opaque', 'clear', 'muddy', 'cloudy', 'foggy', 'misty', 'hazy', 'dim', 'dark', 'shadowy', 'gloomy', 'bleak', 'dismal', 'dreary', 'melancholy', 'sad', 'sorrowful', 'grieving', 'mourning', 'weeping', 'crying', 'sobbing', 'wailing'],
      nouns2: ['truth', 'reality', 'essence', 'core', 'heart', 'soul', 'spirit', 'nature', 'character', 'identity', 'purpose', 'meaning', 'significance', 'importance', 'value', 'worth', 'beauty', 'ugliness', 'goodness', 'evil', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring']
    },
    {
      structure: 'in the {adjective} {noun}, {noun2} {verb} {noun3}',
      adjectives: ['deepest', 'darkest', 'brightest', 'lightest', 'highest', 'lowest', 'farthest', 'nearest', 'oldest', 'newest', 'youngest', 'eldest', 'wisest', 'foolish', 'kindest', 'cruelest', 'gentlest', 'harshest', 'softest', 'hardest', 'sweetest', 'bitterest', 'happiest', 'saddest', 'richest', 'poorest', 'strongest', 'weakest', 'fastest', 'slowest', 'hottest', 'coldest', 'wettest', 'driest', 'heaviest', 'lightest', 'biggest', 'smallest', 'longest', 'shortest', 'widest', 'narrowest'],
      nouns: ['chamber', 'sanctuary', 'temple', 'shrine', 'altar', 'throne', 'palace', 'castle', 'tower', 'fortress', 'citadel', 'stronghold', 'battlement', 'rampart', 'wall', 'gate', 'door', 'portal', 'gateway', 'entrance', 'exit', 'passage', 'corridor', 'hall', 'room', 'chamber', 'cell', 'cave', 'cavern', 'grotto', 'abyss', 'pit', 'well', 'spring', 'fountain', 'pool', 'lake', 'ocean', 'sea', 'river', 'stream', 'brook', 'creek'],
      nouns2: ['oracle', 'prophet', 'sage', 'seer', 'mystic', 'shaman', 'wizard', 'warlock', 'witch', 'enchanter', 'sorcerer', 'magician', 'conjurer', 'diviner', 'augur', 'soothsayer', 'fortune-teller', 'palm-reader', 'astrologer', 'numerologist', 'tarot-reader', 'medium', 'channeler', 'healer', 'teacher', 'guide', 'mentor', 'master', 'guru', 'swami', 'lama', 'monk', 'priest', 'priestess', 'druid', 'bard', 'minstrel', 'troubadour'],
      verbs: ['whispers', 'speaks', 'calls', 'sings', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'breathes', 'lives', 'dies', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites'],
      nouns3: ['secrets', 'mysteries', 'truths', 'lies', 'prophecies', 'predictions', 'foretellings', 'visions', 'dreams', 'revelations', 'omens', 'signs', 'portents', 'auguries', 'divinations', 'oracles', 'messages', 'words', 'phrases', 'sentences', 'verses', 'poems', 'songs', 'chants', 'mantras', 'prayers', 'blessings', 'curses', 'riddles', 'puzzles', 'enigmas', 'paradoxes', 'contradictions', 'harmonies', 'dissonances', 'rhythms', 'melodies', 'symphonies', 'concertos', 'sonatas', 'arias', 'ballads', 'hymns', 'anthems']
    },
    {
      structure: 'the {noun} of {noun2} {verb} like {noun3}',
      nouns: ['voice', 'song', 'whisper', 'shout', 'cry', 'laugh', 'sigh', 'breath', 'wind', 'breeze', 'gust', 'storm', 'thunder', 'lightning', 'rain', 'snow', 'hail', 'sleet', 'frost', 'dew', 'mist', 'fog', 'cloud', 'sun', 'moon', 'star', 'planet', 'comet', 'meteor', 'shooting star', 'constellation', 'galaxy', 'universe', 'cosmos', 'creation', 'destruction', 'beginning', 'end', 'birth', 'death', 'life', 'rebirth'],
      nouns2: ['oracle', 'prophet', 'sage', 'seer', 'mystic', 'shaman', 'wizard', 'warlock', 'witch', 'enchanter', 'sorcerer', 'magician', 'conjurer', 'diviner', 'augur', 'soothsayer', 'fortune-teller', 'palm-reader', 'astrologer', 'numerologist', 'tarot-reader', 'medium', 'channeler', 'healer', 'teacher', 'guide', 'mentor', 'master', 'guru', 'swami', 'lama', 'monk', 'priest', 'priestess', 'druid', 'bard', 'minstrel', 'troubadour'],
      verbs: ['sounds', 'echoes', 'resonates', 'vibrates', 'pulses', 'beats', 'throbs', 'quivers', 'trembles', 'shakes', 'shudders', 'quakes', 'roars', 'howls', 'wails', 'moans', 'groans', 'sighs', 'whispers', 'murmurs', 'mumbles', 'stutters', 'stammers', 'sings', 'chants', 'recites', 'proclaims', 'declares', 'announces', 'reveals', 'discloses', 'confesses', 'admits', 'denies', 'affirms', 'confirms', 'validates', 'invalidates', 'supports', 'opposes', 'helps', 'hinders'],
      nouns3: ['thunder', 'whisper', 'song', 'sigh', 'laugh', 'cry', 'wind', 'breeze', 'storm', 'rain', 'snow', 'hail', 'sleet', 'frost', 'dew', 'mist', 'fog', 'cloud', 'sun', 'moon', 'star', 'planet', 'comet', 'meteor', 'shooting star', 'constellation', 'galaxy', 'universe', 'cosmos', 'creation', 'destruction', 'beginning', 'end', 'birth', 'death', 'life', 'rebirth', 'river', 'stream', 'ocean', 'sea', 'lake', 'pond', 'pool', 'spring', 'well', 'fountain', 'waterfall']
    },
    {
      structure: 'seek the {noun} within the {noun2}',
      nouns: ['truth', 'wisdom', 'knowledge', 'understanding', 'insight', 'foresight', 'hindsight', 'memory', 'forgetting', 'learning', 'teaching', 'growing', 'aging', 'dying', 'living', 'breathing', 'thinking', 'feeling', 'sensing', 'knowing', 'believing', 'doubting', 'hoping', 'fearing', 'loving', 'hating', 'caring', 'ignoring', 'noticing', 'observing', 'watching', 'listening', 'speaking', 'singing', 'dancing', 'moving', 'standing', 'sitting', 'lying', 'walking', 'running', 'flying'],
      nouns2: ['darkness', 'light', 'shadow', 'illumination', 'silence', 'sound', 'stillness', 'motion', 'emptiness', 'fullness', 'absence', 'presence', 'void', 'substance', 'nothingness', 'everything', 'beginning', 'end', 'past', 'future', 'present', 'eternity', 'moment', 'instant', 'second', 'minute', 'hour', 'day', 'night', 'morning', 'evening', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'season', 'year', 'month', 'week', 'decade']
    },
    {
      structure: 'the {noun} {verb} when {noun2} {verb2}',
      nouns: ['oracle', 'prophet', 'sage', 'seer', 'mystic', 'shaman', 'wizard', 'warlock', 'witch', 'enchanter', 'sorcerer', 'magician', 'conjurer', 'diviner', 'augur', 'soothsayer', 'fortune-teller', 'palm-reader', 'astrologer', 'numerologist', 'tarot-reader', 'medium', 'channeler', 'healer', 'teacher', 'guide', 'mentor', 'master', 'guru', 'swami', 'lama', 'monk', 'priest', 'priestess', 'druid', 'bard', 'minstrel', 'troubadour'],
      verbs: ['speaks', 'whispers', 'calls', 'sings', 'dances', 'flows', 'moves', 'shifts', 'changes', 'reveals', 'hides', 'opens', 'closes', 'rises', 'falls', 'turns', 'spins', 'flows', 'breathes', 'lives', 'dies', 'grows', 'decays', 'heals', 'wounds', 'blesses', 'curses', 'helps', 'hinders', 'guides', 'misleads', 'teaches', 'learns', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits', 'unites'],
      nouns2: ['moon', 'sun', 'star', 'planet', 'comet', 'meteor', 'shooting star', 'constellation', 'galaxy', 'universe', 'cosmos', 'creation', 'destruction', 'beginning', 'end', 'birth', 'death', 'life', 'rebirth', 'dawn', 'dusk', 'twilight', 'midnight', 'noon', 'sunrise', 'sunset', 'morning', 'evening', 'night', 'day', 'season', 'year', 'month', 'week', 'decade', 'century', 'millennium', 'eon'],
      verbs2: ['rises', 'sets', 'shines', 'fades', 'glows', 'dim', 'sparkles', 'tarnishes', 'dances', 'stills', 'flows', 'stagnates', 'moves', 'stops', 'changes', 'remains', 'grows', 'shrinks', 'expands', 'contracts', 'opens', 'closes', 'reveals', 'hides', 'shows', 'conceals', 'expresses', 'suppresses', 'releases', 'holds', 'gives', 'takes', 'creates', 'destroys', 'builds', 'breaks', 'mends', 'splits']
    },
    {
      structure: 'the {noun} {verb} through {noun2}',
      nouns: ['wisdom', 'truth', 'light', 'darkness', 'spirit', 'soul', 'heart', 'mind', 'consciousness', 'awareness', 'presence', 'essence', 'energy', 'force', 'power', 'strength', 'courage', 'love', 'hope', 'faith', 'trust', 'belief', 'doubt', 'fear', 'anger', 'hate', 'envy', 'jealousy', 'pride', 'humility', 'gratitude', 'forgiveness', 'mercy', 'justice', 'honesty', 'integrity', 'honor', 'dignity', 'respect', 'admiration', 'appreciation', 'recognition', 'acknowledgment'],
      verbs: ['flows', 'moves', 'travels', 'journeys', 'wanders', 'roams', 'explores', 'discovers', 'penetrates', 'pierces', 'cuts', 'slices', 'divides', 'separates', 'unites', 'connects', 'links', 'binds', 'ties', 'fastens', 'secures', 'releases', 'frees', 'liberates', 'opens', 'closes', 'reveals', 'hides', 'shows', 'conceals', 'illuminates', 'darkens', 'brightens', 'dim', 'sparkles', 'shimmers', 'glows', 'radiates', 'emanates', 'pulsates', 'vibrates', 'resonates', 'echoes', 'reverberates'],
      nouns2: ['veil', 'curtain', 'screen', 'wall', 'barrier', 'boundary', 'limit', 'horizon', 'edge', 'border', 'line', 'divide', 'separation', 'connection', 'bridge', 'gate', 'door', 'window', 'opening', 'passage', 'path', 'road', 'way', 'journey', 'adventure', 'quest', 'mission', 'purpose', 'meaning', 'significance', 'importance', 'value', 'worth', 'beauty', 'ugliness', 'goodness', 'evil', 'reality', 'illusion', 'dream', 'nightmare', 'fantasy', 'fact', 'fiction', 'myth', 'legend', 'story', 'tale', 'narrative']
    },
    {
      structure: 'if {noun} were {adjective}, {noun2} would {verb}',
      nouns: ['time', 'wind', 'shadow', 'moonlight', 'memory', 'dream', 'river', 'mountain', 'song', 'silence', 'flame', 'ocean'],
      adjectives: ['a whisper', 'golden', 'endless', 'fragile', 'hidden', 'restless', 'ancient', 'shimmering', 'gentle', 'wild'],
      nouns2: ['heart', 'soul', 'path', 'sky', 'forest', 'mind', 'sea', 'story', 'petal', 'star'],
      verbs: ['dance', 'sing', 'vanish', 'linger', 'glow', 'wander', 'rise', 'fall', 'echo', 'bloom']
    },
    {
      structure: 'like {noun}, {noun2} {verb} through {noun3}',
      nouns: ['rain', 'glass', 'feathers', 'mist', 'flame', 'shadow', 'wind', 'time'],
      nouns2: ['hope', 'fear', 'light', 'truth', 'joy', 'sorrow', 'memory', 'dream'],
      verbs: ['slips', 'flows', 'weaves', 'glides', 'wanders', 'drifts', 'shimmers', 'echoes'],
      nouns3: ['branches', 'corridors', 'waves', 'valleys', 'echoes', 'clouds', 'threads', 'petals']
    },
    {
      structure: 'no {noun} is too {adjective} for {noun2} to {verb}',
      nouns: ['path', 'river', 'story', 'flame', 'shadow', 'door', 'bridge', 'dream'],
      adjectives: ['long', 'narrow', 'dark', 'bright', 'fragile', 'wild', 'twisted', 'endless'],
      nouns2: ['light', 'wind', 'hope', 'song', 'soul', 'memory', 'truth', 'wave'],
      verbs: ['cross', 'follow', 'chase', 'carry', 'whisper to', 'illuminate', 'guide', 'find']
    },
    {
        structure: 'only when {noun} {verb} will {noun2} {verb2}',
        nouns: ['the tide', 'the lantern', 'the dawn', 'the veil', 'the heart', 'the shadow'],
        verbs: ['returns', 'flickers', 'breaks', 'lifts', 'beats', 'shifts'],
        nouns2: ['truth', 'hope', 'song', 'memory', 'dream', 'story'],
        verbs2: ['bloom', 'emerge', 'fade', 'shine', 'linger', 'awaken']
    },
    {
        structure: 'beyond the {adjective} {noun}, {noun2} {verb}',
        adjectives: ['silver', 'forgotten', 'wild', 'hidden', 'shattered', 'bright'],
        nouns: ['valley', 'horizon', 'shore', 'city', 'path', 'gate'],
        nouns2: ['stars', 'echoes', 'waves', 'flames', 'dreams', 'clouds'],
        verbs: ['gather', 'rise', 'fade', 'sing', 'sleep', 'wander']
    }
  ];

export default PHRASE_TEMPLATES;